### ISSUE TITLE
Move usage instructions to README.md

### ISSUE THREAD

**Issue by ApsOps** [fumblehool/Picsaver#1]
- Keep usage instructions in `README.md` instead of a separate file `Usage.txt`
- Usage instructions seem outdated; update them

**Comment by fumblehool** [comment]
@aps-sids thanks for pointing it out.

**Comment by ApsOps** [comment]
You haven't updated the instructions. Why did you close this?

**Comment by fumblehool** [comment]
i am fixing another bug and will update it shortly.
